- native/src/command/platform_specific/wayland/layer_surface.rs
- sctk/src/application.rs
- sctk/src/event_loop/state.rs
With this I'm able to spawn a fullscreen layer shell surface for each output.
For some reason my application doesn't seem to get output events until I move the mouse (with an initial layer surface that's 1x1 pixel). And if I destroy the initial surface in `Application::new`, it never does.
There should also be a way to run with no initial surface, but I guess it currently relies on an initial surface to initialize an EGL display/context.
> sctk: Improvements for handling outputs

- Cargo.toml
- native/Cargo.toml
This should be handled by `iced_sctk` (and already is, `iced_sctk` enables `iced_native/wayland`, which in turn enables the `sctk` dependency). Allows building libcosmic without an unconditional `sctk` dependency.
> features: Don't always build sctk

- Cargo.toml
- native/src/event.rs
- src/clipboard.rs
- src/element.rs
- src/error.rs
- src/executor.rs
- src/keyboard.rs
- src/lib.rs
- src/mouse.rs
- src/overlay.rs
- src/settings.rs
- src/touch.rs
- src/wayland/mod.rs
- src/widget.rs
- src/window.rs
Restructures the crate in a way, that doesn't cause features to disable other features and linkage between backends and renderers, etc.
Now the `iced` crate can be compiled without any features (though it is not super useful in this state and mostly re-exports iced_native).
Additionally  all renderers can be build free-standing (necessary to use `libcosmic` in `cosmic-comp` , which cannot use any of the existing shells/runtime).
Additionally allows combinations of runtimes and renderers to be selected freely, though many are not compatible with each other as noted in the Cargo.toml. (Though more can be made compatible, e.g. sctk could also work with wgpu or swbuf in the future.)
Required for https://github.com/pop-os/libcosmic/pull/64
> features: Explicit backend/renderer combinations

- src/element.rs
- src/lib.rs
- src/mouse.rs
- src/touch.rs
Turns out `iced_winit`/`iced_glutin`/`iced_sctk` only reexport most of their types from `iced_native`. This PR changes some imports in the main `iced`-crate, so that they use `iced_native` directly or as a fallback to enable building `libcosmic` without any `shell` or `runtime` feature being activated.
> features: Use iced_native types without a runtime

- swbuf/src/backend.rs
Makes the `swbuf` `Backend` type public to make it possible to construct it and iced's `Renderer` out-of-tree to integrate the swbuf backend directly without using one of the provided shells.
> swbuf: Make backend constructor visible

- softbuffer/src/lib.rs
- softbuffer/src/surface.rs
Allows the softbuffer renderer to be used without a surface.
Additionally re-exports the raqote-types for convenience, because they are needed for `draw_primitive`.
> Expose draw_primitive for shell-less rendering

- src/keyboard.rs
Use `iced_native` directly instead of the `runtime`-crate for the keyboard-types.
This fixes compilation of the new `keyboard_nav`-widget in libcosmic, if neither `winit` or `sctk` are enabled.
The same workaround is already used for the `mouse` and `touch` modules. No shell seems to override these keyboard types, all just re-export them from `iced_native` anyway.
> iced: Use iced_native for keyboard types

- examples/autosize_layer/Cargo.toml
- examples/autosize_layer/src/main.rs
- native/src/command/platform_specific/wayland/popup.rs
- sctk/src/application.rs
- sctk/src/event_loop/mod.rs
- sctk/src/event_loop/state.rs
- sctk/src/handlers/compositor.rs
- sctk/src/handlers/shell/layer.rs
- sctk/src/handlers/shell/xdg_popup.rs
- sctk/src/handlers/shell/xdg_window.rs
- sctk/src/sctk_event.rs
- sctk/src/settings.rs
cleanup: fixes visual corruption sometimes present in auto-sized surfaces, and also adds the option for starting without an  initial surface
> fix: iced-sctk

- examples/sctk-drag/src/main.rs
- native/src/widget.rs
- native/src/widget/dnd_source.rs
- native/src/widget/helpers.rs
- native/src/widget/mouse_listener.rs
I realized a simple helper for detecting drag operations could be useful when implementing custom drag and drop operations. I think this will be useful for the app list DnD implementation.
> feat: on_drag handler for mouse_listener

- native/src/widget/dnd_listener.rs
- sctk/src/application.rs
It seems that an empty tree can't always be passed here, and for example lazy widget will panic unless there is some state. Auto sized surfaces will also probably panic with lazy widgets because they also diff an empty tree, so I may need to test them more as well and make a similar fix.
> fix: set drag icon widget state and children state

- core/src/renderer/null.rs
- core/src/text.rs
- core/src/widget/text.rs
- graphics/src/geometry/text.rs
- renderer/src/compositor.rs
- renderer/src/settings.rs
- src/settings.rs
- tiny_skia/src/settings.rs
- wgpu/src/layer.rs
- wgpu/src/settings.rs
- widget/src/checkbox.rs
- widget/src/overlay/menu.rs
- widget/src/pick_list.rs
- widget/src/radio.rs
- widget/src/toggler.rs
- Set default font size to 14
- Default line height to a relative of 1.4
- Default to advanced shaping
> chore: default line height, text size, and shaping for cosmic

- runtime/src/program/state.rs
This handles widget operations in the `State`-helper `cosmic-comp` makes use of. As far as I am aware the window integrations all use the `UserInterface`-type directly, while the `State`-helper was initially conceived for foreign integrations, like the previously existing `integration_opengl` and `integration_wgpu` examples.
`State` is mostly a convenience type around the `UserInterface` building block and hides that behind it's api, so there is no way to call `UserInterface::operate` from the outside. Additionally it returns `Command`-created by the Widget-Tree unprocessed.
Any `Actions::Widget`-variants derived from these `Command`s containing `Operation`s are thus never processed by the internal `UserInterface` and cannot be passed in from the outside.
This PR fixes this short-coming …
> runtime: Handle widget operations in `program::State` helper

- sctk/src/application.rs
- sctk/src/conversion.rs
- sctk/src/sctk_event.rs
The next step will be getting this setting from the environment. I'm not sure if there's a protocol for this that sctk can use to get the value from the compositor, or if we'll need to get this from cosmic-comp's config file in libcosmic.
The winit backend defaults to reverse scrolling, but sctk is defaulting to natural.
> feat(sctk): configurable natural_scroll property

- sctk/src/application.rs
This should prevent unnecessary rebuilds of the interface, but also queue up redraws immediately whenever there is an update needed for the interface.
> fix: redraw when an update is needed and clean up the logic

- Cargo.toml
- core/src/renderer.rs
- sctk/src/application.rs
- sctk/src/event_loop/mod.rs
- src/lib.rs
- style/src/application.rs
- style/src/button.rs
- style/src/container.rs
- style/src/theme.rs
- style/src/theme/palette.rs
- widget/src/button.rs
- widget/src/container.rs
- widget/src/mouse_area.rs
- widget/src/pane_grid/title_bar.rs
- widget/src/scrollable.rs
- widget/src/svg.rs
- widget/src/text_input/text_input.rs
- widget/src/text_input/text_input_wayland.rs
- widget/src/tooltip.rs
- winit/src/application.rs
- winit/src/application/state.rs
Adds a new field to the renderer style to support defining a default icon color for symbolic icons. By default, this color will be set to the same value as the text color for maximum visibility. The color may be overridden by the button or container that it is placed in. Icons marked as symbolic will opt into this color if no color was defined.
Merge with https://github.com/pop-os/libcosmic/pull/150
> feat(renderer): definable default color for symbolic icons

- sctk/src/application.rs
this seems to help CPU usage for app library and launcher
> fix: default to ControlFlow::Wait for applications with no surface

- CHANGELOG.md
- core/src/mouse/button.rs
- sctk/src/conversion.rs
- winit/src/conversion.rs
This PR allows iced to detect back and forward side buttons for mouse devices that supports them, this includes:
- The fourth non-scroll button, which is often used as "back" in web browsers.
- The fifth non-scroll button, which is often used as "forward" in web browsers.
> Detect mouse side buttons

- accessibility/Cargo.toml
This fixes duplicate sctk imports of the same version: 0.16.1 and the patched 0.16.1 for wayland resize
> Update accesskit winit version

- core/Cargo.toml
- examples/sctk_drag/Cargo.toml
- examples/sctk_todos/Cargo.toml
- runtime/Cargo.toml
- runtime/src/command/platform_specific/wayland/activation.rs
- runtime/src/command/platform_specific/wayland/mod.rs
- sctk/Cargo.toml
- sctk/src/application.rs
- sctk/src/commands/activation.rs
- sctk/src/commands/mod.rs
- sctk/src/event_loop/mod.rs
- sctk/src/event_loop/state.rs
- sctk/src/handlers/activation.rs
- sctk/src/handlers/data_device/data_source.rs
- sctk/src/handlers/mod.rs
- widget/Cargo.toml
> Xdg activation

- core/src/image.rs
- graphics/src/backend.rs
- graphics/src/primitive.rs
- graphics/src/renderer.rs
- renderer/src/lib.rs
- tiny_skia/src/backend.rs
- tiny_skia/src/raster.rs
- widget/src/image.rs
- widget/src/image/viewer.rs
Adds a `border_radius` property to the image widget, and the necessary changes to the image renderer to support rendering images with a border radius. To be merged alongside a PR to libcosmic for the ImageButton widget.
> feat: image border radius rendering

- runtime/src/command/platform_specific/wayland/data_device.rs
- sctk/src/application.rs
- sctk/src/commands/data_device.rs
- sctk/src/event_loop/mod.rs
- sctk/src/event_loop/state.rs
- sctk/src/handlers/data_device/data_device.rs
- sctk/src/handlers/data_device/data_source.rs
- sctk/src/sctk_event.rs
The clipboard actually probably should just be handled one way, so I guess not in the iced-sctk loop, or else it can block forever on reading. For example, it might block forever because a widget is using the "iced" method to read after setting the clipboard via the "iced-sctk" method.
> refactor: use iced clipboard for interacting with the selection

- runtime/src/command/platform_specific/wayland/window.rs
- sctk/src/event_loop/state.rs
related to https://github.com/pop-os/libcosmic/pull/203
> refactor: allow passing an activation token when creating a window

- core/src/event/wayland/mod.rs
- core/src/event/wayland/session_lock.rs
- examples/sctk_session_lock/Cargo.toml
- examples/sctk_session_lock/src/main.rs
- runtime/src/command/platform_specific/wayland/mod.rs
- runtime/src/command/platform_specific/wayland/session_lock.rs
- sctk/src/application.rs
- sctk/src/commands/mod.rs
- sctk/src/commands/session_lock.rs
- sctk/src/event_loop/mod.rs
- sctk/src/event_loop/state.rs
- sctk/src/handlers/mod.rs
- sctk/src/handlers/session_lock.rs
- sctk/src/sctk_event.rs
The example creates a session lock surface, but doesn't currently show the contents of the surface correctly. Still figuring that part out. Then some of the smaller details will need some care (making sure to not exit without a round trip, handling the compositor refusing to create lock, etc.)
> sctk: Add support for `ext-session-lock` protocol

- widget/src/dnd_listener.rs
A `dnd_listener` widget shouldn't handle a DnD event when the dnd drag isn't within the widget's bounds. So add a few more checks for this.
Enter/leave events generated by `DndOfferEvent::Motion` also don't behave as one might expect, since the enter may occur before the leave depending on the order it calls `on_event` on the widget. Not sure how to address that, but cosmic-workspaces can just ignore the leave events for now.
Otherwise, this seems to be working fine, after these changes.
> dnd_listener: Fix behavior when there are multiple listeners

- sctk/src/application.rs
Subscriptions should receive surface events
> fix: broadcast surface events

- graphics/src/damage.rs
- graphics/src/primitive.rs
- graphics/src/text.rs
- tiny_skia/src/backend.rs
- tiny_skia/src/text.rs
- wgpu/src/layer.rs
- wgpu/src/layer/text.rs
- wgpu/src/text.rs
Rebase of https://github.com/iced-rs/iced/pull/2158, allows cosmic-edit and cosmic-term to directly render a cosmic-text buffer.
> Introduce `RawText` to `Primitive` in `iced_graphics`

- Cargo.toml
- core/src/renderer/null.rs
- core/src/text.rs
- graphics/src/renderer.rs
- graphics/src/text/editor.rs
- renderer/src/lib.rs
- tiny_skia/src/text.rs
This updates to use the refactor branch of cosmic-text (and glyphon), and allows for cosmic-text buffers to be directly rendered
> Cosmic text refactor

- Cargo.toml
- graphics/src/text.rs
- tiny_skia/src/text.rs
Fixes `Color` to always be in the sRGBA space. Backport from upstream.
> dep: update `glyphon` to `0.4`

- Cargo.toml
This can be tested with something like `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json cargo run -p tour --features iced/wgpu`.
On Nvidia I'm seeing a flood of `Suboptimal present of frame` warnings. So some improvement may still be needed here. But if it doesn't regress behavior on other hardware, that seems like an improvement over freezing.
> Update wgpu to a commit that fixes use on Nvidia drivers

- examples/sctk_subsurface/Cargo.toml
- examples/sctk_subsurface/src/main.rs
- examples/sctk_subsurface/src/wayland.rs
- examples/sctk_subsurface_gst/Cargo.toml
- examples/sctk_subsurface_gst/src/main.rs
- examples/sctk_subsurface_gst/src/pipewire.rs
- sctk/src/application.rs
- sctk/src/event_loop/mod.rs
- sctk/src/event_loop/state.rs
- sctk/src/handlers/mod.rs
- sctk/src/handlers/subcompositor.rs
- sctk/src/lib.rs
- sctk/src/sctk_event.rs
- sctk/src/subsurface_widget.rs
There are a few things I want to clean up here before merging this, and it should have some way for preserving aspect ratio. This went though a few iterations before I found a way to get this working, but now it does.
This defines a `Subsurface` widget that takes a `WlBuffer`, and magically displays it in a Wayland subsurface at the location that widget would appear. This way it can be used in place of an image to display a screencopied dmabuf `WlBuffer`, without copying to CPU or importing into Iced's renderer.
Handling this in Iced is a bit awkward. Iced now supports renderer-specific primitives, but a subsurface like this is "shell-specific" rather than renderer-specific. So there's not clear way for the widget to communicate with the shell. But we can create a side-channel using a …
> `Subsurface` Widget

- winit/src/application.rs
This was particularly visible on Redox where there is no vsync, but also  causes unnecessary redraws on Linux
> Remove unnecessary redraw request

- runtime/src/window.rs
- runtime/src/window/action.rs
- winit/src/application.rs
- winit/src/multi_window.rs
Winit currently supports this only on Windows and Wayland.
This requests that a context menu is shown at the cursor position, like the menu normally triggered by right clicking the title bar. This is important for implementing client side decorations with Iced widgets.
Sent upstream in https://github.com/iced-rs/iced/pull/2243.
> Add `show_window_menu` action

- graphics/src/viewport.rs
- sctk/src/application.rs
- sctk/src/settings.rs
- src/settings.rs
Autosized surfaces perform the layout step to get the size and then again when building the interface, but sometimes the calculated size is not enough space when used as a bound, so we need to add a tiny amount to the calculated size. This also makes the event loop timeout duration configurable. Viewport physical size is calculated directly from the logical size now as well in iced-sctk to avoid inconsistencies that resulted from recalculating the logical size after using it to calculate the physical size.
> fix: autosize surface layout

- examples/sctk_subsurface/src/main.rs
- examples/sctk_subsurface_gst/src/pipewire.rs
- sctk/src/application.rs
- sctk/src/event_loop/mod.rs
- sctk/src/event_loop/state.rs
- sctk/src/handlers/compositor.rs
- sctk/src/handlers/shell/layer.rs
- sctk/src/handlers/shell/xdg_popup.rs
- sctk/src/handlers/shell/xdg_window.rs
- sctk/src/sctk_event.rs
- sctk/src/subsurface_widget.rs
Fixes issue with compositor not redrawing subsurfaces in some cases, avoids creating unnecessary `wl_buffers`s, maps input to subsurfaces with correct offset within window, and other improvements.
> sctk: Fixes for subsurfaces

- sctk/src/application.rs
when broadcasting events for no specific surface, it should be done after update so that the runtime subscription is current. This has been tested with `xdg-desktop-portal-cosmic` and seems to resolve the occasional output mismatch, though, for me, it has been a bit difficult to reproduce even before this commit.
> fix(sctk): broadcast events after update

- Cargo.toml
- sctk/Cargo.toml
- sctk/src/application.rs
- sctk/src/clipboard/clipboard.rs
- sctk/src/clipboard/mod.rs
This updates smithay-clipboard for iced_sctk and makes it optional. None of the applets really need the clipboard, so it could be disabled for them, and should lower cpu usage basically to 0 for many of them like the time applet. I think by default, libcosmic could disable clipboard for applets, but enable it for regular applications.
> refactor(sctk): optional clipboard

- sctk/src/event_loop/state.rs
A null `region` represents an infinite region (the default). To set an empty region, we need to create a `wl_region`.
> sctk: Fix handling of layer surface `pointer_interactivity`

- winit/src/multi_window.rs
Ambiguous import breaks multi-window winit targets
> fix: ambiguous import

- Cargo.toml
- core/Cargo.toml
- core/src/clipboard.rs
- core/src/event.rs
- core/src/widget/tree.rs
- runtime/Cargo.toml
- runtime/src/command/action.rs
- runtime/src/dnd.rs
- runtime/src/lib.rs
- runtime/src/user_interface.rs
- sctk/src/event_loop/mod.rs
- sctk/src/event_loop/state.rs
- sctk/src/handlers/data_device/data_device.rs
- sctk/src/handlers/data_device/data_offer.rs
- sctk/src/handlers/seat/keyboard.rs
- src/application.rs
- src/lib.rs
- src/multi_window/application.rs
- src/sandbox.rs
- widget/Cargo.toml
- winit/Cargo.toml
- winit/src/application.rs
- winit/src/clipboard.rs
- winit/src/lib.rs
- winit/src/multi_window.rs
- winit/src/proxy.rs
This implements DnD via window-clipboard for iced. iced-sctk is not refactored here except to update to the latest version. I think a separate PR updating iced-sctk along with an effort to update the iced-sctk libcosmic apps might be better timed after the alpha release? In any case, this should make it possible to add DnD to cosmic-files.
> feat: winit dnd

- core/src/clipboard.rs
- core/src/widget.rs
- runtime/src/user_interface.rs
- widget/src/column.rs
- widget/src/container.rs
- widget/src/mouse_area.rs
- widget/src/row.rs
- widget/src/scrollable.rs
- winit/src/application.rs
- winit/src/multi_window.rs
- winit/src/multi_window/window_manager.rs
This collects drag destination rectangles after rebuilding the interface and performing the layout step. It advertises the rectangles so that child element's rectangles are prioritized over their parent element's rectangles.
> feat: update advertised drag destinations after rebuilding an interface

- src/application.rs
- src/multi_window/application.rs
- winit/src/application.rs
- winit/src/clipboard.rs
- winit/src/multi_window.rs
> refactor: remove Sync bound for Message

- sctk/src/application.rs
- sctk/src/event_loop/mod.rs
- sctk/src/sctk_event.rs
Fixes cosmic-greeter running persistently.
> Clean up after lock surfaces are destroyed

- sctk/src/application.rs
- sctk/src/subsurface_widget.rs
The first commit fixes a bug in iced-sctk. The second commit is a workaround for compositor issues, but since it seems to work, it's probably cleaner anyway.
> sctk: Drag and drop related fixes

- runtime/src/command/platform_specific/wayland/data_device.rs
- runtime/src/dnd.rs
- sctk/src/commands/data_device.rs
- sctk/src/event_loop/mod.rs
- widget/src/dnd_source.rs
This adds an offset `Vector` as an argument to `on_drag`, and allows passing an offset to `start_drag`.
Some applications using drag and drop want the top left corner of the drag surface (as happens without an offset). But others want the drag surface to be offset based on where the cursor is on the widget when starting the drag. This can just be `-1 * offset`, but may be scaled if the drag surface is a different size from the original widget.
> sctk: Add support for drag-and-drop surface offsets

- wgpu/Cargo.toml
- wgpu/src/window.rs
- wgpu/src/window/compositor.rs
- wgpu/src/window/wayland.rs
I am quite tired of weird workarounds in libcosmic regarding chassis-detection, power_pref and accidentally inheriting environment variables, cosmic-workspaces accidentally turning on the dgpu by using anti-aliasing... the list goes on.
Lets patch iced_wgpu instead and query the compositor for the device to use.
(untested, because I don't have the full libcosmic dev setup with me during the hackfest, please somebody test this with applets and apps before merging.)
> iced_wgpu: query wayland

- core/src/lib.rs
- core/src/widget/tree.rs
- runtime/src/user_interface.rs
This persists widget state associated with widgets assigned custom IDs even when the tree structure changes, but resets state if the custom ID is not found.
I'm not sure of a good way yet to avoid the unsafe code here, but I believe it is sound.
> fix: better handling of state tree

- wgpu/Cargo.toml
- wgpu/src/window.rs
- wgpu/src/window/compositor.rs
After https://github.com/pop-os/iced/pull/138 was merged, iced with the feature wgpu set, no longer compiles on macos.
After some digging it turns out this was due to some wayland dependencies brought in by that PR.
This is a suggested fix to that problem, by changing the conditional compilation attributes added to exclude macos.
> iced_wgpu: don't query Wayland on macos

- core/src/text.rs
- core/src/widget/text.rs
- graphics/src/text.rs
- graphics/src/text/paragraph.rs
- widget/src/checkbox.rs
- widget/src/overlay/menu.rs
- widget/src/pick_list.rs
- widget/src/radio.rs
- widget/src/text_input/text_input.rs
- widget/src/toggler.rs
This allows setting cosmic-text::Wrap, which will be important for some alpha 1 issues. Should be prepared for upstream in the future (cc @hecrj)
> Make text wrap configurable

- sctk/src/application.rs
- sctk/src/event_loop/mod.rs
- sctk/src/event_loop/state.rs
- sctk/src/handlers/seat/pointer.rs
- sctk/src/handlers/seat/seat.rs
* With multiple windows, `SetCursor` is only sent for the focused window. Fixing a flicker between icons when two windows are using different cursors.
* If there is a drag surface, let that surface set the cursor. And not any other.
* Set cursor on `enter`, and when switching between CSDs and app area.
Fixes https://github.com/pop-os/libcosmic/issues/533.
> sctk: Fixes for cursor icon

- wgpu/Cargo.toml
- wgpu/src/window.rs
- wgpu/src/window/compositor.rs
- wgpu/src/window/wayland.rs
- wgpu/src/window/x11.rs
A bunch of fixes for our work-arounds for wgpu's non-existant/broken device selection.
We special case wayland, but we should special case x11 the same way, so e.g. pop-os 22.04. users can use cosmic-store.
Unfortunately the nvidia-xorg-driver doesn't support DRI2, DRI3 or any other way to reliably detect the device node used. So lets rely on the randr-name, which does contain an id and hasn't change ever since this feature was introduce over a decade ago...
(I also have a branch using glutin/egl for detecting the device node, but that is also broken specifically with the nvidia-xorg-driver and nothing else...)
Superseeds https://github.com/pop-os/iced/pull/157
Fixes https://github.com/pop-os/libcosmic/issues/512 and https://github.com/pop-os/cosmic-store/issues/73
Tested with …
> wgpu: Add x11 device detection

- sctk/src/application.rs
- sctk/src/event_loop/mod.rs
- sctk/src/event_loop/state.rs
- sctk/src/sctk_event.rs
Currently produces https://wayland.app/protocols/ext-session-lock-v1#ext_session_lock_surface_v1:enum:error:entry:dimensions_mismatch when used with cosmic-greeter.
The protocol error is fixed by https://github.com/pop-os/cosmic-comp/pull/675
> apply scale to lock surface

- widget/src/mouse_area.rs
Previously the following error cases could happen:
- A double click could leave `drag_initiated` in a `Some`-state, causing movement afterwards to falsely trigger a drag message
- We never reset `drag_initiated`, if we didn't have a `on_release`-message said, which causes similar symptoms
Also instead of updating `drag_initiated` in multiple places for the same event, try to only handle it in the respective `ButtonPressed`/`ButtonReleased` if-conditions once. (With the exception of double-clicks...)
Fixes https://github.com/pop-os/cosmic-comp/issues/797
> mouse_area: Fix on_drag triggers

- widget/src/container.rs
Adds two methods for containers to set the minimum height and width. Defaults to 0.0
> feat(container): add min_height and min_height

- wgpu/Cargo.toml
- wgpu/src/window.rs
- wgpu/src/window/compositor.rs
This does not provide wgpu capabilities, it just ensures the wgpu feature does not need to be disabled when building for Redox.
> Make iced_wgpu build on redox

- winit/src/platform_specific/wayland/winit_window.rs
The core team is busy and does not have time to mentor nor babysit new contributors. If a member of the core team thinks that reviewing and understanding your work will take more time and effort than writing it from scratch by themselves, your contribution will be dismissed. It is your responsibility to communicate and figure out how to reduce the likelihood of this!
Read the contributing guidelines for more details: https://github.com/iced-rs/iced/blob/master/CONTRIBUTING.md
> fix: log warning instead of panicing for current_monitor

- winit/src/program.rs
Should prevent extra events not associated with a tracked window.
> fix: filter out events with no window id, if the window id is needed

- winit/src/platform_specific/mod.rs
- winit/src/platform_specific/wayland/event_loop/mod.rs
- winit/src/platform_specific/wayland/event_loop/state.rs
- winit/src/platform_specific/wayland/mod.rs
- winit/src/platform_specific/wayland/winit_window.rs
- winit/src/program.rs
- winit/src/program/window_manager.rs
Should fix the performance issue in the cosmic-files applet that was pointed out by @git-f0x
> fix(sctk): reduce event spam for redraw requests

- widget/src/slider.rs
This keeps the slider handle a consistent size, fixes the end of the rail, and doesn't seem to cause any visual artifacts based on my tests.
> fix: slider rendering

- runtime/src/window.rs
- winit/src/program.rs
This PR exposes `set_blur` to the user, allowing it to enable blur effects to the window on supported platforms.
> Expose blur to the user

- widget/src/scrollable.rs
This makes the scrollbar width 8, to more closely match designs. Complete design matching would be more complex, since the scrollbar end radius should be a rectangle, unless the end is in white space.
> fix: scrollbar width

- core/src/widget/tree.rs
this can interact with the named IDs, and cause state mismatches, and doesn't need to be done, because the ID will be updated by the diff method if there is a Tag match anyways.
> fix: avoid overwriting id when diffing children

- winit/src/platform_specific/wayland/handlers/seat/keyboard.rs
`cosmic-osd` expected this event, but it wasn't being sent. This isn't hard to fix, unless there's some non-obvious issues that this was commented to avoid (that is still applicable).
> Send `KeyboardEventVariant::Enter` on keyboard enter

- winit/src/program.rs
This seems to avoid rounding errors that cause configure/resize loops for certain autosize windows.
> fix: request logical size when autosizing

- winit/src/program.rs
It looks like a couple of Windows-specific lines in iced_winit weren't updated to work with the current code. I think this should be right (at least, it fixes compiling on Windows), but it should probably get a double-check before merging.
There are still a few Windows bugs ([#593](https://github.com/pop-os/libcosmic/issues/593) and [#536](https://github.com/pop-os/libcosmic/issues/536)), but I don't know if they are related to this (reasonably sure the first one isn't, not sure about the second one).
> fix: correct event types for Windows

- winit/src/application/drag_resize.rs
The current check for winit drag-resize support relies on calling `window.drag_resize_window()` on startup and seeing if an error is returned. Despite [the warning in the API documentation](https://docs.rs/winit/latest/winit/window/struct.Window.html#method.drag_resize_window) that calling this function without a left mouse button click happening does not guarantee that a drag-resize will actually be triggered, on Windows this does appear to trigger a drag-resize event ([see libcosmic issue #593](https://github.com/pop-os/libcosmic/issues/593)). Unfortunately, I don't see another way in winit to dynamically check for this support at runtime.
This PR replaces the current check with a check of a constant variable set at compile time.
> fix: Replace current drag-resize support check with hard-coded support values

- winit/src/platform_specific/wayland/sctk_event.rs
- winit/src/program.rs
This avoids issues with apps like the portal that creates a screenshot, sets the clipboard, and then has the data device destroyed when the window is closed.
> fix: use dummy window for clipboard

- graphics/src/compositor.rs
- renderer/src/fallback.rs
- tiny_skia/src/window/compositor.rs
- wgpu/src/window/compositor.rs
- winit/src/platform_specific/mod.rs
- winit/src/platform_specific/wayland/mod.rs
- winit/src/platform_specific/wayland/sctk_event.rs
- winit/src/platform_specific/wayland/subsurface_widget.rs
- winit/src/program.rs
Fixes for issues I see in cosmic-workspaces, when trying to update to latest iced rebase.
Still not working for subsurfaces of drag surfaces...
> `subsurface_widget` fixes

- Cargo.toml
- winit/Cargo.toml
- winit/src/platform_specific/mod.rs
- winit/src/platform_specific/wayland/mod.rs
- winit/src/platform_specific/wayland/subsurface_widget.rs
- winit/src/program.rs
Use `Icon::Surface` instead of `Icon::Buffer`, so we can then create subsurfaces of the `wl_surface`.
Using `.screenshot()` then copying to an shm buffer is suboptimal, but this does seem overall better than with the older Iced version when a drag surface didn't appear until a Vulkan surface could be created for it.
This seems to be working okay now, but there are a few things to fix. As well as a bug I'm seeing in cosmic-comp. `cosmic-workspaces` also wants the `offset` support for drag surfaces we previously had.
> Subsurfaces for drag surfaces

- core/src/clipboard.rs
- runtime/src/dnd.rs
- winit/src/clipboard.rs
- winit/src/platform_specific/mod.rs
- winit/src/platform_specific/wayland/mod.rs
- winit/src/platform_specific/wayland/subsurface_widget.rs
- winit/src/program.rs
Provides the same functionality as https://github.com/pop-os/iced/pull/134.
Still needs `libcosmic` update to pass on offset on drag start, and provide a way to set the offset of the surface. This also doesn't seem to be working as expected currently....
This also tries to clean up the way a tuple and `Box<dyn Any>` was used to be a little more organized.
> Add support for drag-and-drop surface offsets

- Cargo.toml
libcosmic uses 0.25, so this will prevent duplicate of image crates.
> chore: update image to 0.25

- wgpu/src/window/compositor.rs
This somewhat improves performance on resizing by using the cached self.alpha_mode on the wgpu backend instead of calling surface.get_capabilities every time, which results in a roughly 50% reduction in resize draw time.
Note: resizing is still somewhat choppy and I've traced it to surface.configure in the same function, though I cannot figure out why this takes many times longer to run than base iced. If I figure it out, I'll let y'all know
> Use cached alpha mode instead of calling surface.get_capabilities every time the window is redrawn

- winit/src/platform_specific/wayland/event_loop/state.rs
- winit/src/platform_specific/wayland/subsurface_widget.rs
Is there a reason we don't support fractional scaling for the subsurfaces that wrap a buffer source? I've continued to leave that out here, but this seems to fix some scaling issues in the lock screen and greeter.
> fix: create fractional scale for sctk subsurfaces

- widget/src/text/rich.rs
- winit/src/platform_specific/wayland/event_loop/state.rs
This ensures that rich text only captures mouse presses if there are links defined.
> Fix rich text widget capturing all mouse presses

- core/src/layout.rs
- core/src/overlay.rs
- widget/src/button.rs
- widget/src/column.rs
- widget/src/container.rs
- widget/src/keyed/column.rs
- widget/src/pane_grid.rs
- widget/src/pane_grid/title_bar.rs
- widget/src/row.rs
- widget/src/scrollable.rs
This will probably affect future rebases, but I think something like this must be done for widgets to create popups and sub-surfaces at the correct position using the Layout. This, along with some changes to libcosmic, fixes https://github.com/pop-os/cosmic-settings/issues/1067.
> refactor: include virtual offset in Layout

- runtime/src/platform_specific/wayland/subsurface.rs
- winit/src/platform_specific/wayland/event_loop/mod.rs
- winit/src/platform_specific/wayland/event_loop/state.rs
- winit/src/platform_specific/wayland/handlers/seat/keyboard.rs
- winit/src/platform_specific/wayland/sctk_event.rs
- winit/src/platform_specific/wayland/subsurface_widget.rs
In the protocol specification for `wl_subsurface::place_above` :
> This sub-surface is taken from the stack, and put back just above the reference surface, changing the z-order of the sub-surfaces. T
So we don't need to place above all previous subsurfaces; in fact, this can mess up the order when there are more than two subsurfaces.
Looks like the place this is called also needs a fix; `attach_and_commit` is where `z` is set for new surfaces, so we need to make sure that `z` value is used when updating the order (though it should also be before the `.commit()`.
I think we should also have a way to place subsurfaces *behind* the parent surfaces. Probably making `z` and i32, and placing subsurfaces with negative indices behind the parent surface would work.
> subsurface_widget: Fix use of `place_above`, allow negative `z` to place below parent surface

- winit/src/platform_specific/wayland/handlers/seat/pointer.rs
- winit/src/platform_specific/wayland/sctk_event.rs
Fixes https://github.com/pop-os/cosmic-workspaces-epoch/issues/143.
The way some events are converted to `WindowEvent`s in `pointer_frame` but motion is handled in `SctkEvent::process` seems a little cluttered at the moment, I guess from how this code was ported to be part of iced-winit instead of separate. But as I understand, the code handling `PointerEventKind::Enter` in `SctkEvent::enter` wasn't being called, so that can be replaced with the new code here that sets the logical cursor position.
> wayland: Set cusor position on `Enter` events

- winit/src/program.rs
This should fix https://github.com/pop-os/cosmic-epoch/issues/1734
What it avoids is the case where the control flow is set to wait until some instant that then passes, wakes up the event loop, and then there is nothing to do so it just loops on that same instant, which makes it effectively equivalent to `ControlFlow::Poll` unless it is reset.
> Fix control flow

- core/src/keyboard/modifiers.rs
- winit/src/platform_specific/wayland/conversion.rs
- winit/src/platform_specific/wayland/subsurface_widget.rs
This will not track Caps Lock on other platforms but should give cosmic-greeter and the pkexec gui what they need.
Some unrelated code was formatted in another commit.
> support CapsLock modifiers on wayland

- winit/src/platform_specific/wayland/event_loop/state.rs
- winit/src/platform_specific/wayland/subsurface_widget.rs
This reverts commit 15547dec8f83af1ea6dbed1964302400fc17c257 from https://github.com/pop-os/iced/pull/227.
This is causing issues in `cosmic-workspaces`. It seems I didn't test it properly outside the examples here... and this misinterpreted exactly what the (undocumented) `viewport` argument means (Iced's `image` widget also needed a fix to handle viewports properly since our fork: https://github.com/iced-rs/iced/pull/2752).
It should be possible to fix, but revert for now.
> Revert "subsurface_widget: Handle `viewport` and set source rectangle"

- winit/src/platform_specific/wayland/sctk_event.rs
Ideally pointer should be seperate from touch, but this should match how Iced handles input in normal winit windows.
https://github.com/iced-rs/iced/blob/d475ae5b454b82cb549d6dd961ae158eb5ac7f19/winit/src/window/state.rs#L165-L170
With this, touch input for applets seems to work as expected in general.
> winit/sctk: Update cursor position on touch event
