style/src/cosmic/theme.rs
style/src/expander.rs
style/src/lib.rs

Added styles for the `Expander` widget

Expander style

---

native/src/command/platform_specific/wayland/popup.rs
native/src/command/platform_specific/wayland/window.rs
native/src/event/wayland/layer.rs
native/src/event/wayland/popup.rs
native/src/event/wayland/seat.rs
sctk/src/application.rs
sctk/src/commands/window.rs
sctk/src/event_loop/mod.rs

This adds several improvements to window handling in iced-sctk.
window drags, window resize, window toggle maximized & fullscreen, window minimization, window app id, and fixes a typo that prevented windows from notifying the application about being closed

feat: various improvements to window commands and event handling

---

examples/todos_sctk/src/main.rs
native/src/event/wayland/output.rs
native/src/widget/mouse_listener.rs
sctk/src/commands/window.rs
sctk/src/conversion.rs
sctk/src/event_loop/mod.rs
sctk/src/handlers/output.rs
sctk/src/handlers/shell/xdg_window.rs
sctk/src/sctk_event.rs
swbuf/src/backend.rs
swbuf/src/surface.rs
swbuf/src/window/compositor.rs

This forwards output events and ran cargo fmt

feat: sent output events

---

native/src/widget/button.rs
src/widget.rs
style/src/button.rs
style/src/theme.rs

Required by https://github.com/pop-os/libcosmic/pull/69 (which will then require updating the submodule)

Add focus operation and style for button

---

sctk/src/application.rs

For some reason this was an issue testing with `iced_glow`/`glutin`, but this also fixes the issue I was having where the application doesn't get output events if I destroy the initial surface and create surfaces later.
The use of `ManuallyDrop` seems dubious, but I see that's also in parts of upstream Iced and is a workaround for a borrow checker limitation. Looks like there's some progress on that in Rustc though.

sctk: Send output events to application even with no surface configured

---

sctk/src/application.rs

Fixes behavior with `InitialSurface::None`.

sctk: Send output events even if no surface exists

---

examples/integration_opengl/src/main.rs
examples/integration_wgpu/src/main.rs
glutin/src/application.rs
native/src/renderer.rs
native/src/widget/button.rs
native/src/widget/container.rs
native/src/widget/pane_grid/title_bar.rs
native/src/widget/tooltip.rs
sctk/src/application.rs
winit/src/application.rs

This allows images to be generated at the right scale

Expose scale factor of viewport in renderer::Style

---

widget/src/dnd_source.rs

This seems like the easiest way to allow an application to scale a drag surface to match the item being dragged from. Which it seems we want to do in cosmic-workspaces.
This is a breaking API change, but easy enough to adjust to.

dnd_source: Pass size of source widget to `on_drag`

---

core/Cargo.toml
examples/sctk_drag/Cargo.toml
examples/sctk_drag/src/main.rs
examples/sctk_todos/Cargo.toml
runtime/Cargo.toml
sctk/Cargo.toml
sctk/src/application.rs
sctk/src/event_loop/mod.rs
sctk/src/event_loop/state.rs
sctk/src/handlers/data_device/data_source.rs
widget/Cargo.toml

chore: update sctk

---

examples/sctk_drag/src/main.rs
sctk/src/application.rs

This should be ok even for widget actions like focus next because there can only ever be a single focused widget

fix: make sure that each widget operation operates on every interface

---

core/Cargo.toml
core/src/keyboard/key_code.rs

This allows for saving/loading KeyCodes as part of configs, for key bindings.

iced_core: feature for serde serialization of KeyCode

---

wgpu/src/image.rs

See https://github.com/iced-rs/iced/pull/1491, this is required for cosmic-edit in the short term

Hack to remove image blur

---

sctk/src/application.rs
src/settings.rs
src/wayland/mod.rs

This is trying to fix the build error of https://github.com/pop-os/libcosmic/pull/212

Remove Clone constraint on Flags

---

style/src/slider.rs
style/src/theme.rs
widget/src/slider.rs

Implements optional breakpoints to display beneath a slider. This is a breaking change for libcosmic.

feat(slider): add breakpoints

---

sctk/src/event_loop/mod.rs

This should help fix https://github.com/pop-os/cosmic-applibrary/issues/78

fix(sctk): destroy drag icon and send event after cancel action

---

futures/src/subscription.rs

Fixes polkit agent in cosmic-osd release build. And probably other things.

Cherry-pick fix for subscriptions running twice

---

Cargo.toml
core/Cargo.toml
core/src/clipboard.rs
core/src/element.rs
core/src/widget/tree.rs
graphics/src/text/editor.rs
runtime/Cargo.toml
runtime/src/clipboard.rs
sctk/Cargo.toml
sctk/src/application.rs
sctk/src/clipboard/clipboard.rs
sctk/src/clipboard/mod.rs
src/lib.rs
style/src/theme.rs
widget/src/keyed/column.rs
widget/src/pane_grid.rs
winit/src/application.rs
winit/src/clipboard.rs
winit/src/multi_window.rs

I'll add some new actions and commands too.

feat: custom mime types for Clipboard

---

sctk/src/application.rs
sctk/src/sctk_event.rs

Map subsurface to parent and add offset.

sctk: Fix handling of DnD with subsurfaces

---

widget/src/container.rs
widget/src/scrollable.rs
winit/src/multi_window.rs

This was causing diff to fail when updating state after the tree changed.

fix(container): id and set_id should use content

---

runtime/src/clipboard.rs
src/lib.rs
winit/src/clipboard.rs

This adds read_primary / write_primary to match the regular read / write clipboard operations.

Add read_primary/write_primary

---

Cargo.toml
core/src/keyboard/modifiers.rs
tiny_skia/src/backend.rs

the issue can be seen with sharp corners when using the screenshot portal with scaling

fix(tiny-skia): non-simple border scaling

---

winit/src/clipboard.rs

fixes https://github.com/pop-os/libcosmic/issues/417

fix: update read and write methods so they don't recurse

---

wgpu/src/window/compositor.rs
wgpu/src/window/wayland.rs

Draft because ~~this needs testing and a new vulkan loader version in pop-os~~. Done and done.

Fix nvidia card powering up in hybrid setups

---

wgpu/src/window/compositor.rs

Closes https://github.com/pop-os/libcosmic/issues/490

fix: unset VK_LOADER_DRIVERS_DISABLE after enumeration

---

Cargo.toml
sctk/src/event_loop/mod.rs
sctk/src/event_loop/state.rs
sctk/src/handlers/compositor.rs
sctk/src/subsurface_widget.rs

Sctk will need to be updated in a few other libraries as well.

sctk: `Subsurface` fix, and alpha modifier support

---

runtime/src/command/platform_specific/wayland/window.rs
sctk/src/application.rs

Should allow creating windows with regular actions when using iced-sctk and more.

refactor(sctk): convert window actions

---

runtime/src/command/platform_specific/wayland/window.rs
sctk/src/event_loop/mod.rs

Enables the window menu to appear in COSMIC Settings

feat(sctk): support ShowWindowMenu

---

Cargo.toml
widget/src/mouse_area.rs

This is required to support double click to maximize ( https://github.com/pop-os/libcosmic/issues/323 and https://github.com/pop-os/cosmic-comp/issues/333).

feat(mouse area): add double click

---

tiny_skia/src/backend.rs

Addresses the comment left on [9d9d078](https://github.com/pop-os/iced/commit/9d9d0786edfba5cc862315f63a8b6eb21370f912)

Fix quad fill radius calculation

---

widget/src/pane_grid.rs
widget/src/pane_grid/content.rs

This is needed to implement dragging files into COSMIC Term and having the file paths inserted.
https://github.com/pop-os/cosmic-term/issues/86

Add drag destinations for pane grid

---

core/src/mouse/click.rs

For details checkout my comment on cosmic-files: https://github.com/pop-os/cosmic-files/issues/575#issuecomment-2408974015
Note: asked the maintainer of iced in discord and he is fine with such a change, so this could potentially upstreamed.
Fixes https://github.com/pop-os/cosmic-files/issues/575

Introduce double_click_distance like other toolkits such as Gtk,Qt,imgui.

---

Cargo.toml
winit/src/platform_specific/wayland/handlers/toplevel.rs

Requires https://github.com/pop-os/cosmic-protocols/pull/49.

winit/wayland: Update for toplevel-info cctk changes

---

widget/src/text_editor.rs

Upstream PR: https://github.com/iced-rs/iced/pull/2653
This is used in my app bodev: https://bodev.sgued.fr/

Add focus id to text editor

---

winit/src/platform_specific/wayland/sctk_event.rs

This will fix https://github.com/pop-os/cosmic-applibrary/issues/218

fix: send pointer motion event for pointer enter event

---

examples/list/Cargo.toml
examples/list/src/main.rs
widget/src/helpers.rs
widget/src/lib.rs
widget/src/list.rs

Squashed and cleaned up so it can be applied to our fork
Draft until it compiles and is tested

Infinite `List` widget from upstream feature/list-widget-reloaded branch
